# Generated by Django 3.0.8 on 2020-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogowanie', '0002_auto_20200712_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
