# Generated by Django 3.0.8 on 2020-07-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogowanie', '0006_auto_20200718_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_blog',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Blogowanie.Blog'),
        ),
    ]
